config/routes.rb
Rails.application.routes.draw do
  root'flights#index', as: 'flights'
  get 'flights/index'
  resources :bookings, only: [:new, :create, :index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, :foreign_key => "departure_airport_id", class_name: "Flight"
  has_many :arriving_flights, :foreign_key => "arrival_airport_id", class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers
  accepts_nested_attributes_for :passengers

end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, :class_name => "Airport"
  belongs_to :arrival_airport, :class_name => "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings

  def date_formatted
    departure_time.strftime("%m/%d/%Y")
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  before_save { email.downcase! }
  belongs_to :booking
  has_many :flights, through: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  @@env = Spreedly::Environment.new(ENV["CORE_ENVIRONMENT_KEY"], ENV["CORE_ACCESS_SECRET"])
  @@gateway = @@env.find_gateway(ENV["GATEWAY_KEY"])

  def new
    @booking = Booking.new
    @flight = Flight.find(params[:flight_id])
    @num_passengers = params[:num_passengers].to_i
    @total_price = @flight.price * @num_passengers
    @num_passengers.times {@booking.passengers.build}
    @credit_cards = @@env.list_payment_methods
  end

  def create

    begin
      puts params[:payment_method_token]
      @flight = Flight.find(booking_params[:flight_id].to_i)
      @num_passengers = params[:booking][:num_passengers].to_i
      @total_price = @flight.price * @num_passengers
      trx = @@env.purchase_on_gateway(@@gateway.token, params[:payment_method_token], @total_price.to_i * 100)
      if params[:storage_state]
        @@env.retain_payment_method(params[:payment_method_token])
      end
      if trx.succeeded?
        @booking = Booking.new(booking_params)
        @booking.trx_id = trx.token
        if @booking.save
          flash[:success] = "Booked!"
          @@env.deliver_to_receiver(
            ENV["RECEIVER_KEY"],
            params[:payment_method_token],
            headers: { "Content-Type": "application/json" },
            url: "https://spreedly-echo.herokuapp.com",
            body: {'test': 'test'}
          )
          redirect_to @booking
        else
        flash[:error] = trx.message
        @booking = Booking.new
        @num_passengers.times {@booking.passengers.build}
        render :new
        end
      else
        flash[:error] = trx.message
        @booking = Booking.new
        @num_passengers.times {@booking.passengers.build}
        render :new
        end
      end
    rescue Exception => ex
      flash[:error] = ex.message
      @booking = Booking.new
      @num_passengers.times {@booking.passengers.build}
      render :new
    end


  def index
    @bookings = Booking.all
    @transactions = @@env.list_transactions

    puts @transactions.last.token
    puts @transactions.last.succeeded
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private
    def booking_params
      params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email, :booking_id])
    end

    def credit_card_params
      params.require(:credit_card).permit(:first_name, :last_name, :number, :month, :year, :storage_state)
    end
end

app/controllers/flights_controller.rb
include ActionView::Helpers::TextHelper


class FlightsController < ApplicationController
  def index
    @airports_options = Airport.all.map{|a| [ "#{a.code}, #{a.name}", a.id ]}
    @num_passenger_options = [1,2,3,4].map{|num| [ pluralize(num, 'person'), num ]}
    @departure_time_options = Flight.select(:departure_time).group('DATE(departure_time)').map{ |f| [ f.date_formatted, f.departure_time.to_date ]}

    @num_passengers = params[:num_passengers] unless params[:num_passengers].nil?
    @queried_flights = []
    if !params[:departure_airport_id].nil?
      @queried_flights = Flight.all
      @queried_flights = @queried_flights.where(departure_airport_id: params[:departure_airport_id])
      @queried_flights = @queried_flights.where(arrival_airport_id: params[:arrival_airport_id])
      @queried_flights = @queried_flights.where("DATE(departure_time) = ?", params[:departure_time].to_date)
    end

  end


  private

    def flight_params
      params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :departure_time, :num_passengers)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/index.html.erb
<h1>Bookings</h1>

Upcoming Reservations:
<ul>
  <% @bookings.each do |booking| %>
    <li>
      <%= link_to "Booking ##{booking.id}", booking %> |
      Flying out of: <%= booking.flight.departure_airport.name %> |
      Flying to: <%= booking.flight.arrival_airport.name %> |
      Departure time: <%= booking.flight.departure_time %> |
      Flight duration: <%= booking.flight.duration %>
      Passengers: <% booking.passengers.each do |p| %>
        <%= p.name %>
      <% end %>
    </li>
  <% end %>
</ul>

<ul>
  <% @transactions.each do |transaction| %>
  <li>
    Transaction Token: <%= transaction.token %> |
    Transaction Success/Failure: <%= transaction.succeeded %> |
    Transaction Message: <%= transaction.message %>
  </li>
  <% end %>
</ul>

<%= link_to "Find another flight", flights_path %>

app/views/bookings/new.html.erb
<%= javascript_pack_tag 'hide' %>
<h1>Booking Information</h1>

<div>
  <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
  <% end %>
  <%= form_for(@booking) do |f| %>
  <%= f.hidden_field :flight_id, value: params[:flight_id] %>
  <%= f.hidden_field :num_passengers, value: @num_passengers %>
  <%= f.hidden_field :total_price, value: @total_price %>

    Departing from: <%= @flight.departure_airport.name %> |
    Arriving to: <%= @flight.arrival_airport.name %> |
    Date: <%= @flight.departure_time %> |
    Price: <%= @total_price %>
    <%= pluralize(@num_passengers, "passenger") %>

    <ul>
      <%= f.fields_for :passengers do |passenger_form| %>
        <li>
          <%= passenger_form.label :name %>
          <%= passenger_form.text_field :name, required: true %>
          <%= passenger_form.label :email %>
          <%= passenger_form.email_field :email, required: true %>
        </li>
      <% end %>
    </ul>
      <input type="hidden" name="payment_method_token" id="payment_method_token">
      <input type="button" value="Enter Payment Info" onclick="SpreedlyExpress.openView();">
      <input id="retain" name="credit_card[storage_state]" type="checkbox" value="true" />
      <label for="retain">Save card for future use?</label>
    <div>
      <%= submit_tag "Create Booking" %>
    </div>
  <% end %>
</div>

<%= link_to "Back to search", flights_path %>

app/views/bookings/show.html.erb
<h1>Booking information</h1>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
<ol>
  <li>Flying out of: <%= @booking.flight.departure_airport.name %></li>
  <li>Flying to: <%= @booking.flight.arrival_airport.name %></li>
  <li>Departure time: <%= @booking.flight.departure_time %></li>
  <li>Flight duration: <%= @booking.flight.duration %></li>
  <li>
    Passengers:
    <ul>
      <% @booking.passengers.each do |p| %>
      <li> <%= p.name %> </li>
      <% end %>
      </ul>
  </li>
</ol>
<%= link_to "See all bookings", bookings_path %>

app/views/flights/index.html.erb
<h1>Search for a flight:</h1>

<%= form_tag(flights_path, method: :get) do %>
<div class = "form row">
  <%= label_tag "Departs from:" %>
  <%= select_tag(:departure_airport_id, options_for_select(@airports_options, params[:departure_airport_id])) %>
</div>
<div class = "form row">
  <%= label_tag "Arrives at:" %>
  <%= select_tag(:arrival_airport_id, options_for_select(@airports_options, params[:arrival_airport_id])) %>
</div>
<div class = "form row">
  <%= label_tag "Departure date:" %>
  <%= select_tag(:departure_time, options_for_select(@departure_time_options, params[:departure_time])) %>
</div>
<div class = "form row">
  <%= label_tag "Number of passengers:" %>
  <%= select_tag(:num_passengers, options_for_select(@num_passenger_options, params[:num_passengers])) %>
</div>

<div class = "form">
  <%= submit_tag "Search for flights" %>
</div>
<% end %>
<% unless @queried_flights.empty? %>
  <h3>Select from:</h3>

  <%= form_tag new_booking_path, method: :get do %>
    <%= hidden_field_tag :num_passengers, params[:num_passengers] %>
    <% @queried_flights.each do |flight| %>
      <div class = "form row">
        <%= radio_button_tag(:flight_id, "#{flight.id}", :required => true) %>
        <%= label_tag("flight_id_#{flight.id}", "#{flight.departure_airport.name}") %> |
        <%= label_tag("flight_id_#{flight.id}", "#{flight.arrival_airport.name}") %> |
        <%= label_tag("flight_id_#{flight.id}", "Departure date: #{flight.date_formatted}") %> |
        <%= label_tag("flight_id_#{flight.id}", "Duration: #{pluralize(flight.duration, 'hour')}") %>
        <%= label_tag("flight_id_#{flight.id}", "Price per ticket: #{flight.price}") %>
      </div>
    <% end %>
    <div class = "form">
      <%= submit_tag "Book flight" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <script src="https://core.spreedly.com/iframe/express-3.min.js"></script>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>